openapi: 3.0.0
info:
    description: >
        Documentation for *Deliveryman* library at
        [https://github.com/bravepickle/deliveryman](https://github.com/bravepickle/deliveryman).
    version: "1.0.0-oas3"
    title: Deliveryman API
    termsOfService: 'http://swagger.io/terms/'
    contact:
        email: 2bravepickle@gmail.com
    license:
        name: Apache 2.0
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

# TODO: for each channel provide separate definition docs
paths:
    /http_queue/batch:
        post:
            summary: Create new batch of requests
            operationId: createBatch
            responses:
                '200':
                    description: Successfully completed
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BatchResponse'
                '400':
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                type: string
                '401':
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: string
            security:
                - api_key: []
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BatchRequest'
                description: List of request data and their configurations to execute
                required: true
externalDocs:
    description: Find out more
    url: 'https://github.com/bravepickle/deliveryman'
servers:
    - url: 'https://virtserver.swaggerhub.com/bravepickle/deliveryman/1.0.0'
    - url: 'http://virtserver.swaggerhub.com/bravepickle/deliveryman/1.0.0'
components:
    securitySchemes:
        api_key:
            type: apiKey
            name: api_key
            in: header
    schemas:
        BatchRequest:
            type: object
            description: Batch request body
            properties:
                config:
                    $ref: '#/components/schemas/RequestConfig'
                data:
                    type: array
                    items:
                        $ref: '#/components/schemas/Queue'
        BatchResponse:
            type: object
            description: Batch response body
            properties:
                status:
                    type: string
                    description: 'Result status code: ok, aborted, failed.'
                data:
                    type: array
                    description: 'Return responses that succeeded.'
                    items:
                        $ref: '#/components/schemas/Response'
                errors:
                    type: object
                    additionalProperties: true
                failed:
                    type: array
                    items:
                        $ref: '#/components/schemas/Response'
        RequestConfig:
            type: object
            properties:
                headers:
                    type: array
                    description: List of requests to send together with request
                    items:
                        $ref: '#/components/schemas/RequestHeader'
                    default: []
                config_merge:
                    type: string
                    description: Configs merge strategy per request
                    default: first
                    enum:
                        - first
                        - unique
                        - ignore
                on_fail:
                    type: string
                    description: Strategy on handling failed requests
                    default: abort
                    enum:
                        - abort
                        - proceed
                        - abort-sequence
                expected_status_codes:
                    type: array
                    description: >-
                        List of all status codes that are considered OK, if returned. If any
                        other status codes received by requests, then request is considered
                        as failed
                    items:
                        type: integer
                    default:
                        - 200
                        - 201
                        - 202
                        - 204
                silent:
                    type: boolean
                    description: Do not return response data from batch requests back to sender
                    default: false
        Queue:
            type: array
            items:
                $ref: '#/components/schemas/Request'
        Request:
            type: object
            description: Request data to send
            properties:
                id:
                    type: string
                    description: Identifier for given request for referencing aka alias
                uri:
                    type: string
                    description: Target URI to send data to
                method:
                    type: string
                    description: HTTP method to use for sending request
                config:
                    $ref: '#/components/schemas/RequestConfig'
                headers:
                    type: array
                    description: List of requests to send together with request with disregard to config merging strategy
                    items:
                        $ref: '#/components/schemas/RequestHeader'
                query:
                    type: array
                    description: List of query params passed with request
                    items:
                        $ref: '#/components/schemas/RequestQuery'
                data:
                    $ref: '#/components/schemas/RequestData'
        RequestQuery:
            type: object
            description: Query key-value pairs for request
            additionalProperties: true
            example:
                query: Search word
                ids: [1, 2]
        RequestData:
            type: object
            description: Data specified in body of request
            additionalProperties: true
        ResponseData:
            type: object
            description: Data specified in body of response
            additionalProperties: true
        RequestHeader:
            type: object
            description: Request HTTP headers to send to request
            properties:
                name:
                    type: string
                    description: Name of the HTTP request header
                value:
                    type: string
                    description: Value of the HTTP request header
        Response:
            type: object
            description: Response data returned by requests.
            properties:
                id:
                    type: string
                    description: Identifier for initial request
                headers:
                    type: array
                    description: List of returned headers
                    items:
                        $ref: '#/components/schemas/RequestHeader'
                data:
                    $ref: '#/components/schemas/ResponseData'